steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/capstone-api', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/capstone-api']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gcloud', 'run', 'deploy', 'capstone-api', '--image', 'gcr.io/$PROJECT_ID/capstone-api', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']
